# Generated by Django 6.1 on 2026-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmss', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
